# Uncomment this if your project is hosted on GitHub:
# github_url = "https://github.com/<user or organization>/<project>/"

[version]
current = "0.2.78"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = "pyproject.toml"
[[file]]
src = "auto_dev/commands/deps.py"
[[file]]
src = "auto_dev/data/repo/templates/autonomy/pyproject.toml.template"
[[file]]
src = "auto_dev/data/repo/templates/python/pyproject.toml.template"
[[file]]
src = "adev_config.yaml"

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

[[before_commit]]
name = "Ensure lock of generated repo"
cmd = "bash scripts/check_generated.sh"

  

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
