# This is a basic workflow to help you get started with Actions

name: Code Quality
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11.5"]
        poetry-version: ["1.3.2"]
        os: [ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          installer-parallel: true

      - name: Install CI dependencies
        run: |
          bash install_deps.sh
          # wget https://github.com/protocolbuffers/protobuf/releases/download/v24.3/protoc-24.3-linux-x86_64.zip
          # unzip protoc-24.3-linux-x86_64.zip -d protoc
          # sudo mv protoc/bin/protoc /usr/local/bin/protoc
          # wget https://github.com/yoheimuta/protolint/releases/download/v0.27.0/protolint_0.27.0_Linux_x86_64.tar.gz && \
          # tar -xvf protolint_0.27.0_Linux_x86_64.tar.gz && \
          # sudo mv protolint /usr/local/bin/protolint

      - name: Install Adev
        run: |
          bash auto_dev/data/repo/templates/autonomy/install.sh

      - name: Format
        run: |
          poetry run adev -n 0 -v fmt -p .

      - name: Lint
        run: |
          poetry run adev -n 0 -v lint -p .

      - name: Tests
        run: |
          poetry run adev -v test -p .
