# This is a basic workflow to help you get started with Actions

name: Dependency Workflows
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request_target:
    types:
      - opened
    branches:
      - 'main'
      - 'master'
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_deps:
    strategy:
      matrix:
        python-versions:
        - "3.10"
        os:
        - ubuntu-20.04
    runs-on: ubuntu-20.04
    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          installer-parallel: true

      - name: Install ci dependencies
        run: |
          make install

      - name:
        run: |
          make test

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./coverage-report.txt


      - name: Update Readme with Coverage Html
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

      - name: Commit & Push changes to Readme
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Lock application deps
        run: |
          poetry lock

