name: Documentation Build Check
on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocstrings[python]
          pip install mkdocs-include-markdown-plugin
          pip install mkdocs-mermaid2-plugin
          pip install -e .

      - name: Build MkDocs
        run: mkdocs build --strict