name: Release on Main

# Triggers the workflow on push events to the main branch
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  release_on_main:
    runs-on: ubuntu-latest
    needs: check   # Ensures this job only runs after the "check" job is completed successfully
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'Bump to 0.2.110') # Optional condition to skip some commits

    permissions:
      contents: write   # Allows modifying repository content (including workflows

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.0.1
          virtualenvs-create: true
          installer-parallel: true

      - name: Install Adev
        run: |
          make install

      - name: Run release if on main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "CI"
          git config --global user.email "ci@station.codes"
          poetry run adev release --auto-approve
